language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install numpy
  - pip install Pillow
  - pip install coverage
script:
  - coverage run test.py
after_success:
  - coverage report -m