language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install numpy
  - pip install Pillow
  - pip install coverage
  - pip install tensorflow
script:
  - coverage run test.py
after_success:
  - coverage report -m